image: python:3.6.8

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
